--
-- PostgreSQL database dump
--

\restrict iyO1JgrgWAhHSU5OZe0WBqZBJeT4wCFXhq5ylRMlqfYys8AHGMc1JtveOmez2Jj

-- Dumped from database version 16.13
-- Dumped by pg_dump version 18.3 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO app;

--
-- Name: link; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.link (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    url character varying(3000) NOT NULL,
    collection_id_id integer NOT NULL
);


ALTER TABLE public.link OWNER TO app;

--
-- Name: link_collection; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public.link_collection (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    public boolean NOT NULL,
    user_id_id integer NOT NULL
);


ALTER TABLE public.link_collection OWNER TO app;

--
-- Name: link_collection_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.link_collection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.link_collection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: link_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public.link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: app
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    username character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public."user" OWNER TO app;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: app
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260412211909	2026-04-16 11:46:24	19
\.


--
-- Data for Name: link; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.link (id, name, url, collection_id_id) FROM stdin;
\.


--
-- Data for Name: link_collection; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public.link_collection (id, name, public, user_id_id) FROM stdin;
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: app
--

COPY public."user" (id, username, roles, password) FROM stdin;
1	admin	["ROLE_ADMIN"]	$2y$13$qLWG9xbo5sLkssEaBuBZx.0/7c.VgM.lRxPOwibfxTi1HfFII.dti
\.


--
-- Name: link_collection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.link_collection_id_seq', 1, false);


--
-- Name: link_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.link_id_seq', 1, false);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: app
--

SELECT pg_catalog.setval('public.user_id_seq', 1, true);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: link_collection link_collection_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.link_collection
    ADD CONSTRAINT link_collection_pkey PRIMARY KEY (id);


--
-- Name: link link_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.link
    ADD CONSTRAINT link_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_36ac99f138bc2604; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX idx_36ac99f138bc2604 ON public.link USING btree (collection_id_id);


--
-- Name: idx_abc7a5c79d86650f; Type: INDEX; Schema: public; Owner: app
--

CREATE INDEX idx_abc7a5c79d86650f ON public.link_collection USING btree (user_id_id);


--
-- Name: uniq_identifier_username; Type: INDEX; Schema: public; Owner: app
--

CREATE UNIQUE INDEX uniq_identifier_username ON public."user" USING btree (username);


--
-- Name: link fk_36ac99f138bc2604; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.link
    ADD CONSTRAINT fk_36ac99f138bc2604 FOREIGN KEY (collection_id_id) REFERENCES public.link_collection(id);


--
-- Name: link_collection fk_abc7a5c79d86650f; Type: FK CONSTRAINT; Schema: public; Owner: app
--

ALTER TABLE ONLY public.link_collection
    ADD CONSTRAINT fk_abc7a5c79d86650f FOREIGN KEY (user_id_id) REFERENCES public."user"(id);


--
-- PostgreSQL database dump complete
--

\unrestrict iyO1JgrgWAhHSU5OZe0WBqZBJeT4wCFXhq5ylRMlqfYys8AHGMc1JtveOmez2Jj

