<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412211909 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(3000) NOT NULL, collection_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_36AC99F138BC2604 ON link (collection_id_id)');
        $this->addSql('CREATE TABLE link_collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, public BOOLEAN NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ABC7A5C79D86650F ON link_collection (user_id_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F138BC2604 FOREIGN KEY (collection_id_id) REFERENCES link_collection (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE link_collection ADD CONSTRAINT FK_ABC7A5C79D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE link DROP CONSTRAINT FK_36AC99F138BC2604');
        $this->addSql('ALTER TABLE link_collection DROP CONSTRAINT FK_ABC7A5C79D86650F');
        $this->addSql('DROP TABLE link');
        $this->addSql('DROP TABLE link_collection');
        $this->addSql('DROP TABLE "user"');
    }
}
